### ISSUE TITLE
Image size parameter

### ISSUE THREAD

**Issue by herkulano** [tmoerman/sourire#1]
It would be nice to have a parameter to set the height or width of the image or both.
In case of both it would resize the image according to the lowest value.

**Comment by tmoerman** [comment]
Hi Herc, this is possible.

For example: 

http://localhost:8000/molecule/CN1CCC%5BC%40H%5D1c2cccnc2?render-image-width=400&render-image-height=200

or

http://localhost:8000/molecule/CN1CCC%5BC%40H%5D1c2cccnc2?render-image-size=400,200

What Sourire does is simply relay the url parameters to the underlying Indigo renderer. Possible parameters are described here: http://scitouch.net/up/indigo-doc/indigo/options/index.html

Actually I should put this in the readme... 

Hope this is useful.
T

**Comment by herkulano** [comment]
that's great! thank you.
